### ISSUE TITLE
(EUR 40) Implement events from Completes Wizard, Books Call trigger

### ISSUE THREAD

**Issue by espruyt** [tunga-io/tunga-web#118]
##

## I'm submitting a ...

<pre><code>
[ ] Bug report 
[*x* ] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Expected behavior

In Hubspot CRM, offline leads are processed manually. But online leads are largely processed automatically. To make sure that online leads are up to date in Hubspot, a number of events should trigger a mutation in Hubspot:

1. Client completes wizard on Tunga.io, books call
Should trigger:
- for this client a new ID/file is created in Hubspot containing all available data (e-mail, name, etc)
- lifecycle stage should be set to ‘Opportunity’
- owner should be set to Domieck
- a (custom) tag should be added to this client ID named ‘wizard call’
- a Deal should be created named after the client + id# (First Contact deal stage)

## What is the motivation / use case for changing the behavior?

- This will make sure the Hubspot CRM is always up to date
- It will save a lot of time as otherwise this should be done manually

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>
https://docs.google.com/document/d/10YtZ-o6GdCNXL6Qw1-f2D7gsQQZOi6ewaX2iiK6zBZU/edit

**Comment by espruyt** [comment]
@davidsemakula 
--> a Deal should be created named after the client + id# (First Contact deal stage)
this is already happening but the deal just gets a number. this is not convenient. prefer the deal to be named after the client or the company; which ever is available + id# (in case one client post multiple deals)

**Comment by davidsemakula** [comment]
Other info will be addressed by https://github.com/tunga-io/tunga-api/issues/23
