### ISSUE TITLE
Pop up (slide in from right side)

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#123]

**Comment by bartleijssenaar** [comment]
##

## I'm submitting a ...

<pre><code>
[ ] Bug report 
[*x* ] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior



## Expected behavior


In Hubspot CRM, offline leads are processed manually. But online leads are largely processed automatically. To make sure that online leads are up to date in Hubspot, a number of events should trigger a mutation in Hubspot:

1. Client completes wizard on Tunga.io, books call
Should trigger:
- for this client a new ID/file is created in Hubspot containing all available data (e-mail, name, etc)
- lifecycle stage should be set to ‘Opportunity’
- owner should be set to Domieck
- a (custom) tag should be added to this client ID named ‘wizard call’
- a Deal should be created named after the client + id# (First Contact deal stage)

## Minimal instructions for reproducing the problem (optional for feature requests)


## What is the motivation / use case for changing the behavior?


- This will make sure the Hubspot CRM is always up to date
- It will save a lot of time as otherwise this should be done manually

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development


For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>
https://docs.google.com/document/d/10YtZ-o6GdCNXL6Qw1-f2D7gsQQZOi6ewaX2iiK6zBZU/edit

**Comment by davidsemakula** [comment]
@bartleijssenaar shouldn't the pop-up slide in from the right?
current description says left

**Comment by bartleijssenaar** [comment]
Correct, right side. I've edited the feature request

**Comment by davidsemakula** [comment]
https://www.screenmailer.com/v/cnmx1I6ahV5UAfg
