### ISSUE TITLE
Amount of money shown on the task

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#13]
Currently, the full sum of money that the project owner sets on a pledge for a task is shown on the task (card & page). This is not the amount the developer is going to receive. The developer(s) will receive 87% of the task and 13% goes to Tunga. 

FOR PROJECT OWNERS: 

on the "post a task page" is must be presented clearly (see redesign post a task page). 13% of the pledge goes to Tunga. 

FOR DEVELOPERS:

On the task card and task page the pledge must be 87% of the actual pledge submitted by the project owners.

FOR THE PAYMENT:

the full amount has to be loaded in the lightbox.

**Comment by bartleijssenaar** [comment]
I think we can close this one ;-)

**Comment by davidsemakula** [comment]
I left it open because of this line

> on the "post a task page" is must be presented clearly (see redesign post a task page). 13% of the pledge goes to Tunga.
