### ISSUE TITLE
Project execution - Progress report missed

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#131]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Currenltly we cant track whether surveys have been submitted on our platform in Klipfolio

## Expected behavior

We need a be able to track;

Scheduled surveys / progress reports (this week)
Schedules surveys / progress reports (today)
Missed surveys / progress reports (last week)
Missed surveys / progress reports (yesterday)

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by Domieck** [comment]
@bartleijssenaar also see issue summary report
