### ISSUE TITLE
Schedule a call possibility on the project/task page 

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#142]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Currenly when users want to schedule a call they have to use calendly. Giving this is via a third party service we can't track which project is attachted to with call. This is why we want to have a better call integration in the wizard AS WELL as on the project page. 

## Expected behavior

Flawless booking of a time slot from the wizard AND project page. 

See attachment: 
[schedule call update.pdf](https://github.com/tunga-io/tunga-web/files/1119723/schedule.call.update.pdf)

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by davidsemakula** [comment]
@bartleijssenaar I think we should still get the name and email for `Schedule a call` (Calendly replacement)
This would of course be skipped for the project page

**Comment by bartleijssenaar** [comment]
I agree please add them
