### ISSUE TITLE
Adjust number of hours on pricing page on workload row

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#145]
## I'm submitting a ...

<pre><code>
[X] Bug report (sort of) 
[ ] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Wrong numbers

## Expected behavior

See document
https://docs.google.com/spreadsheets/d/1qNdyztNsOKTTSplo-V9WCb6GfPNuhct_-Mf_wcvtv3I/edit#gid=1384090694

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by davidsemakula** [comment]
@bartleijssenaar from the sheet, it looks like it's not just the workload numbers, can you confirm this?
Also some of the words on the left are different from the pricing page, do you want those to change as well?

**Comment by bartleijssenaar** [comment]
Yes please, change them. @davidsemakula
