### ISSUE TITLE
CTA appears in navbar when you scroll past the CTA on the lander

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#146]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

When you scroll down our landing page the CTA "Start your project" is not always visible 

## Expected behavior

When you scroll down on the lander past this point  (see attachment)
![when to insert cta in navbar](https://user-images.githubusercontent.com/12690878/27898017-0fba493c-6224-11e7-9509-ad45cf85fad9.jpg)
the CTA needs to appear in the navbar. 

For design see: quality, pricing, story page. 

## Please tell us about your environment (optional for feature requests)

<pre><code>

**Comment by davidsemakula** [comment]
https://www.screenmailer.com/v/cnmx1I6ahV5UAfg
