### ISSUE TITLE
Survey feedback implementation

### ISSUE THREAD

**Issue by Domieck** [tunga-io/tunga-web#147]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

1. Currently, we have only yes or no answers to the survey questions sent out to clients. 
2. If the answer to the question whether the deadline was met is no, it still asks the clients whether they were happy with the deliverables.
3. Currently the date for surveys is fixed. 

## Expected behavior

1. Clients have indicated they would like to have to opportunity answer "partly" on all questions that now have only the yes or no variations. In other words, every question that shows YES/NO as possible answers will also be joined by PARTLY,
2. Make sure this is interactive; if deadline is not met, no further questions will be asked about the deliverable. If deadline is met, questions about the quality of the deliverables will be asked. 
3. Make date for surveys flexible, as follows;
    - As soon as the client, opens the survey, there should be in button in the beginning that shows _I'd  
       like to fill this in later_. This only account for the survey while a milestone isn't met yet
     - Another survey should be sent out as soon as a milestone deadline has passed on the platform.

## What is the motivation / use case for changing the behavior?

Improvement surveys

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by davidsemakula** [comment]
@Domieck can u make this more actionable
i.e Change X to Y, Add Z

If we still figuring out what we need to do, let's hold those discussions on Slack

For example we don't have a Sprint feature, we do have milestones though
