### ISSUE TITLE
Skills approval

### ISSUE THREAD

**Issue by Domieck** [tunga-io/tunga-web#149]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Currently, developers are onboarded to project and we're unofficially check their skills. 

## Expected behavior

The desired behavior would be to implement a clickable button on to the platform that once a developer is added to the relevant projects they will be working or are working on, the PM and Tunga staff member is asked whether the skills have been approved (either through previous projects or test)

As a PM/Admin, upon adding a developer to a project/task, I need to make sure the skills are verified.

The following pop up would allow for quick confirmation:

_The developer has been approved in one of the following ways:
 - By the Tunga onboarding procedure
- A skills testing platform
- Has worked on Tunga tasks succesfully before

Confirm_

The user will select one of the options and press confirm. 

As an admin, I also want to have access to what has been indicated before.

As a developer, I will receive a notification that my skills have been approved by Tunga/PM. Tunga will receive a slack notification that the skills have been approved.

Notification developer
" Hi [NAME DEVELOPER],

Congratulations! Your skills have approved by Tunga. Happy coding!

Cheers,

Tunga"

Notification updates channel Tunga slack:

"The skills of [NAME DEVELOPER] have been approved by [NAME ADMIN/PM]."

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by Domieck** [comment]
@bartleijssenaar since we're working with internal approval for now, I'd thought about going over it like this. WDYT?

**Comment by davidsemakula** [comment]
@Domieck I don't think this is quite ready
If otherwise, shouldn't the pop up at least get the details of how the testing was done?

**Comment by Domieck** [comment]
Fair point. @davidsemakula can you check the above ASAP?

**Comment by davidsemakula** [comment]
We good now, motivation clear 👍

**Comment by davidsemakula** [comment]
Addressed by https://github.com/tunga-io/tunga-web/issues/189
