### ISSUE TITLE
admin notification to email 2

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#15]
As an admin I must receive an email when a new task is posted:

details that need to be in the notification must be:

Title:
description
deadline
skills
updates
millstones

**Comment by davidsemakula** [comment]
Updates and milestones not yet available ... so closing this for now

**Comment by bartleijssenaar** [comment]
Are the other ones (description
deadline
skills) tackled?

**Comment by bartleijssenaar** [comment]
I think it better to leave it open, because it is still a to do
