### ISSUE TITLE
Pop up for developers at beginning of survey

### ISSUE THREAD

**Issue by Domieck** [tunga-io/tunga-web#152]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Developers are made aware of the survey and fill in accordingly. There is no reminder that part of the information will be shared with the clients

## Expected behavior

Before they start the survey, I want a pop up window to appear that warns them that some of the information might directly be shared with the client and therefore they should take this into account in their answers.

For example:

_Hi [NAME DEVELOPER],
Please take into account that some of these answers might directly be distributed with clients. Therefore, please always consider if your answers are business/client appropriate. Thank you for filling in the survey!_

## What is the motivation / use case for changing the behavior?

Decrease the number of inappropriate answers being sent to clients

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by davidsemakula** [comment]
@Domieck perhaps we should also indicate which responses in the developer survey will be shared with clients
Please you could add a list of these to the feature request

Thanks

**Comment by Domieck** [comment]
For now, I'd like to keep it with all, until I've adjusted the surveys.
