### ISSUE TITLE
Dynamic pages CMS 

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#153]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[x] BIG AND URGENT Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Currently, we have dynamic content based on the adgroups we use in Adwords. An example of an current dynamic page: /?dlp_tag=Android&dlp_desc=developers

This is NOT enough for Google to make us relevant for our visitor, therefore we need to create unique content for all dynamic pages. We will create a lot of landers for each ad group. An overview of these ad groups can be found here: 

## Expected behavior

I've created a design in which multiple sections will be presented, in each section there will be assets (text, picture, or cards). I will break each section down and explain the assets and how this should be integrated into the CMS. 

Goal: Build a CMS in the Django admin environment that is accessible for admin users of Tunga.

An admin user should be able to add/insert content for each asset. 
@davidsemakula can you advise on the best structure for this.

As mentioned in this document (row 3) there are a number of assets that an admin should be able to full in or upload. 

**1st section - big picture lander**

1st asset - Header
Text - room for 50 characters (field in CMS)
Font: Fira Sans 
Font-size: 7.8 (or adapt font size so text fits on 2 lines)
Font-weight: Inherit from tunga.io
Color: ![#ffffff](https://placehold.it/15/ffffff/000000?text=+) `#ffffff`

2nd asset - Subheader
Text - room for 100 characters (field in CMS)
Font: Fira Sans 
Font-size: 2.2 (or adapt font size so text fits on 2 lines)
Font-weight: Inherit from tunga.io
Color: ![#ffffff](https://placehold.it/15/ffffff/000000?text=+) `#ffffff`

3rd asset - CTA (call to action)
Text - room for 30 characters (field in CMS)
Font: Fira Sans 
Font-size: 2.2 
Font-weight: 300
Color: ![#ffffff](https://placehold.it/15/ffffff/000000?text=+) `#ffffff`
*note: text should fall on one line and whitin in the box.

**2nd section**

1st asset - Header
Text - room for 80 characters (field in CMS)
Font: Fira Sans 
Font-size: 2.8 (or adapt font size so text fits on 2 lines)
Font-weight: 600
Color: ![#444](https://placehold.it/15/444/000000?text=+) `#444`

1st asset - Text
Text - room for 450 characters (field in CMS)
Font: Fira Sans 
Font-size: 1.5 (or adapt font size so text fits on 2 lines)
Font-weight: 400
Color: ![#444](https://placehold.it/15/444/000000?text=+) `#444`

**3rd section - press**

Inherit the code of the icons from tunga.io

Change the icons to black and white (you can use this: https://www.w3schools.com/cssref/css3_pr_filter.asp) and adjust the opacity to 0.8

**4th section - developers cards**

3 cards must be shown based on the tags (e.g on the ios page 3 ios developers must be shown).

In the CMS the admin should be able to select the profiles he want to input (need a search and/or selections option)

Inherit data shown in the card based on developer selected:
Name - font weight 400 - #444
Location (city and country) font weight 300 #444
4 (2 shown is design) skill tags #fff 
Intro text (inserted by admin)
CTA - view full profile. Puclic profile pages are being build for now you can link this to tunga.io/start

**5th section - how it works**

Inherit code from tunga.io

**6th section detail text-**

1st asset - Header
Text - room for 50 characters - max 2 lines (field in CMS)
Font: Fira Sans 
Font-size: 2.8 (or adapt font size so text fits on 2 lines)
Font-weight: 600
Color: ![#444](https://placehold.it/15/444/000000?text=+) `#444`

1st asset - Text
Text - room for unlimited characters (field in CMS)
Font: Fira Sans 
Font-size: 1.4 
Font-weight: 300
Color: ![#444](https://placehold.it/15/444/000000?text=+) `#444`

Picture:
Option to upload picture
Fixed width of 300 and height of 800
Position: left (see design below)

**Footer**

Inherit from tunga.io

See also #146 for navbar functionality. 

Design:

All responsive and mobile friendly:
Spacing between sections 130 px 

![dynamicpagefinal](https://user-images.githubusercontent.com/12690878/27985738-773a4386-63f1-11e7-83b4-dd4aef118b06.jpg)

## What is the motivation / use case for changing the behavior?

1. More relevant content for our users
2. Higher quality score on Google
3. SEO

**Comment by davidsemakula** [comment]
@bartleijssenaar missing link for ad groups document

**Comment by davidsemakula** [comment]
Addressed by https://github.com/tunga-io/tunga-web/issues/167 on the frontend

**Comment by bartleijssenaar** [comment]
@ponty96 @davidsemakula I got a design update. I can't upload a psd file here. So I will transfer that via Slack.

Here the jpeg
![plp](https://user-images.githubusercontent.com/12690878/28208628-fcc8c30a-688e-11e7-93e7-f924d30e02df.jpg)

**Comment by davidsemakula** [comment]
@ponty96 I've updated the sample API response to reflect changes to the CMS by this design

**Comment by davidsemakula** [comment]
@ponty96 see this issue for relevant details summarized breakdown for the dynamic landing pages from your perspective https://github.com/tunga-io/tunga-web/issues/167
