### ISSUE TITLE
(EUR 30) Notification survey missed

### ISSUE THREAD

**Issue by Domieck** [tunga-io/tunga-web#155]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Currently, we're pretty much in the dark for when an user (either DEV/PM/Client) does not fill in a survey. 

## Expected behavior

Everytime an user misses a survey, we receive the following notification in our #updates slack channel:

" [USER]* has not filled in the survey before the survey deadline."

*Specific to the user who was supposed to fill in the survey.

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by davidsemakula** [comment]
Will be addressed by https://github.com/tunga-io/tunga-api/issues/24
