### ISSUE TITLE
Project planning template 

### ISSUE THREAD

**Issue by Domieck** [tunga-io/tunga-web#158]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Skipping this, as I'm not aware to what extent other issues cover some of it already. Will just add the template. 

## Expected behavior

Upon inception of a project, we want the devs/PM's to produce the report in this file: 
[Project plan template.xlsx](https://github.com/tunga-io/tunga-web/files/1138352/Project.plan.template.xlsx)

Unfortunately, the X/Y values of the Excel template are acting up, but please take note that the table on the left is interactive with the graph on the right, showing how long each task is running in the project. I will incorporate this later with the issue of the timeline. 

## What is the motivation / use case for changing the behavior?

Giving a better overview of the actual breakdown (time wise) of the project.

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by Domieck** [comment]
@bartleijssenaar Could you have a look at the template attached and provide feedback if necessary? Also, let me know if you get the interactive element, as the graph is acting up in the current file.

**Comment by bartleijssenaar** [comment]
[templateplanning.xlsx](https://github.com/tunga-io/tunga-web/files/1200015/templateplanning.xlsx)
[templateplanning.pdf](https://github.com/tunga-io/tunga-web/files/1200014/templateplanning.pdf)

@Domieck @davidsemakula 

Which issue is for visual timeline on the workflow page? Or should I create a new one?

**Comment by Domieck** [comment]
I'm still very much in favor to  indeed create a visual timeline as you've just mentioned. I think this looks good and is very much in sync of what we're using now. Now, we need to find a location for it in the workflow.

**Comment by bartleijssenaar** [comment]
Yes, the client will see it in the workflow environment. 

But we will exclude some options (btns) before he agrees or disagrees with the proposal. 

This will be in the design as well..

**Comment by bartleijssenaar** [comment]
The file is in Zeplin @davidsemakula. I need to explain it to the developer tho.
