### ISSUE TITLE
Feedback form actionable events drip mails

### ISSUE THREAD

**Issue by Domieck** [tunga-io/tunga-web#161]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

In the previously issued actionable dripmails, there was a reference to a feedback form.

E.g.:

_"Hi [USER]

It seems that a deadline on your [NAME PROJECT] project has been missed. We apologize sincerely for the inconvenience this may have caused. This email is to notify you that we will be contacting you very soon to discuss the details of it and how we can help in resolving this very quickly.

Best regards,

Tunga

In case you do not want us to contact you or you have already been helped with this matter, please click the button below.
Button option at end of email stating DEADLINE WAS NOT MISSED/I DO NOT NEED TO BE CONTACTED"_

**For each of these mails we need to establish a feedback form on the platform and a button.
These need to be sent out to the three relevant users: PM's, clients, and developers.**

However, each email has a different button (if applicable - in this case it would be as indicated above) and every feedback form on the platform has a different title. In this case, the title of the feedback form would be: Feedback deadline missed. For every actionable event, keep the title short as referenced. For instance, "Feedback quality rating", "Feedback communication", etc.

Every single feedback form should lead to a screen (after being filled in). **"Thank you for the feedback. You'll hear from us soon."**

Below you find the feedback form per actionable event per user.

**1. In case of missed deadline, not communicated**
Developer:
Please share details about missing the deadline in the form below. 

PM:
Please share details about missing the deadline in the form below. We shall be contacting you shortly.

**2. In case of missed deadline but communicated**
Client:
In case you wish to share some details with us about the missed deadline, feel free to share them with us in the form below.

Developer:
Please share details about missing the deadline in the form below. We shall be contacting you shortly.

PM:
Please share details about missing the deadline in the form below. We shall be contacting you shortly.

**3. Negative difference of 20% or more between percentage time passed and percentage finished of deliverable**

Developer:
Please indicate below if you will still be able to meet the deadline.
[two pre-filled options]
- I will still meet the deadline
- I will not meet the deadline 

[In case of the latter being selected - a feedback form opens up below]

You've indicated that you will not meet the deadline. Please explain below why you will not be able to deadline and how we can possible support you.

**4. Unsatisfied with deliverable**
Developer:
[NAME CLIENT] has indicated that the deliverable was not up to the expected standard. If you have any details, please share them in form below.

PM:
[NAME CLIENT] has indicated that the deliverable was not up to the expected standard. If you have any details, please share them in form below.

**5. Rating deliverable**
Developer:
It seems that there is a large discrepancy between how you rated your deliverables on the [CLIENT’S PROJECT] project and how [NAME CLIENT] has rated it. If you have any additional details, please let us know in the for below.

PM:
Developer:
It seems that there is a large discrepancy between how you rated your deliverables on the [CLIENT’S PROJECT] project and how [NAME CLIENT] has rated it. If you have any additional details, please let us know in the for below.

**6. Status stuck**
Developer:
You've let us know that you're currently stuck with your project. Please share some details with us in the form below.

PM:
You've let us know that you and/or one of the developers in your tribe are currently stuck with your project. Please share some details with us below.

**7. Not anticipating to meet deadline**
Developer:
You've let us know that you expect to miss the deadline. Please share some details with us in the form below.

PM:
You've let us know that you expect to miss the deadline. Please share some details with us in the form below.

**8. If % finished according to client is < than % according to dev/pm**
Developer:
[NAME CLIENT] has let us know that the deliverable on the [CLIENT’S PROJECT] project does not fully meet the agreed specifications. Please share some details with us in the form below.

PM:
Developer:
[NAME CLIENT] has let us know that the deliverable on the [CLIENT’S PROJECT] project does not fully meet the agreed specifications. Please share some details with us in the form below.

## Expected behavior

In 

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by Domieck** [comment]
@davidsemakula Can you peer review this description? It might need more details if a different developer is working on this.

**Comment by davidsemakula** [comment]
@Domieck goal here should be to define the Feedback form for each email (emails are already implemented)

What questions/ responses should the feedback form contain for each email?

**Comment by Domieck** [comment]
@davidsemakula I'm updating per actionable event feedback form feature request at the moment. Feel free to feedback the first ones in the meanwhile.
