### ISSUE TITLE
Footers

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#164]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Only our tunga.io & tunga.io/welcome have a footer

## Expected behavior

Insert footers to all pages before loggin in

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by davidsemakula** [comment]
@bartleijssenaar does this include authentication and wizard pages? we've decided to go in the opposite direction in the past
https://tunga.io/start/
httpa://tunga.io/signin

**Comment by bartleijssenaar** [comment]
no this doesnt include the authentication and wizard pages
