### ISSUE TITLE
Hours logging functionality

### ISSUE THREAD

**Issue by Domieck** [tunga-io/tunga-web#166]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

The current hour logging architecture (or what is in the pipeline for implementation) is as follows:

<img width="584" alt="screen shot 2017-07-13 at 17 08 20" src="https://user-images.githubusercontent.com/29754632/28173301-b7800d96-67f6-11e7-8a7c-e077da0478f7.png">

This screen is the screen for the developer. The one for the client/pm/admin (which is also in the pipeline for the implementation) should remain the same, just as this one.

## Expected behavior

Few suggested enhancements:
- It should be available for **all (except fixed fee tasks)** tasks and projects. In case of projects, the time should show per task (provide breakdown when clicking on the project in the overview for the client). 
- Every first time client should receive a notification about the timesheets and where to find them. Will add text later (@david can you add instructions to that text).
- Let's set as default option that a client receives a notification after every 10 hours of development (feel free to suggest an alternative number for default). However, let's make implement an option where the client can also indicate a different number. Thus, for the user, it should show somewhere (@david @bartleijssenaar happy to hear suggestions where) "I wish to receive a report every [DAY/WEEK] on the number of development hours and/or every [NUMBER TO FILL IN BY USER] hours of development work."

- If the timesheet has not been used for 48 hours, either for a single task or task within a project, Tunga should receive a slack message saying "[NAME DEVELOPERS] has not enabled timesheets for the last 48 hours."

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by Domieck** [comment]
@bartleijssenaar happy to hear constructive suggestions on how to bulletproof this a bit more.

**Comment by Domieck** [comment]
Also, I want to suggest a maximum development hour limit/notification (in case limit is not feasible). This might not be necessary considering that a client approves an estimate, but maybe it allows a client to deal with the first chunk of development hours first. E.g. "I want to be notified if the total amount of development hours hits [NUMBER OF HOURS] hours.

**Comment by davidsemakula** [comment]
> It should be available for all tasks and projects. In case of projects, the time should show per task (provide breakdown when clicking on the project in the overview for the client).

@Domieck I don't this should be enabled by default for tasks/ projects with a fixed fee ... should be opt-in IMO

**Comment by Domieck** [comment]
@davidsemakula I agree
