### ISSUE TITLE
(EUR 50) Update current lander

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#168]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Not applicable

## Expected behavior

https://tunga.io/ should display this design:

![lander](https://user-images.githubusercontent.com/12690878/28211517-609b635c-689d-11e7-8a0e-25fa12df4a21.jpg)

Details about font size are mention in the PSD file, which will be transferred with Slack
Also, a folder with assets will be provided

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by bartleijssenaar** [comment]
![bg1](https://user-images.githubusercontent.com/12690878/28211978-ac7a70a4-689f-11e7-806b-885b589b3c85.jpg)
![bg2](https://user-images.githubusercontent.com/12690878/28211979-ac7b292c-689f-11e7-8f45-6e8693eeaa96.jpg)
![bg3](https://user-images.githubusercontent.com/12690878/28211980-ac7f7f5e-689f-11e7-9756-158d3e10d698.jpg)

**Comment by bartleijssenaar** [comment]
Icons can not be uploaded here

**Comment by bartleijssenaar** [comment]
![tungaexplainer](https://user-images.githubusercontent.com/12690878/28216413-f1a474ba-68b1-11e7-90fd-2ea5ade44718.jpg)

**Comment by bartleijssenaar** [comment]
![youtubevid](https://user-images.githubusercontent.com/12690878/28216504-3b917c9e-68b2-11e7-90dc-aae5d63e5686.jpg)

**Comment by davidsemakula** [comment]
@ponty96 here's the current landing page component https://github.com/tunga-io/tunga-web/blob/develop/src/routes/LandingPage.jsx the variation with a form (wizard lander) already inherits from this component and swaps out the header https://github.com/tunga-io/tunga-web/blob/develop/src/routes/TaskWizardLander.jsx
