### ISSUE TITLE
Explore possibilities for Git integrations on Tunga

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#17]
We want to integrate several Git platform into Tunga. 

Please explore the possibilities to 

Have a GitHub bot in Tunga that updates you on:

Comments
Commit

And 

If we can sync data of an issue to a task on Tunga. 

data:

Title
Description

**Comment by bartleijssenaar** [comment]
@davidsemakula Is going to send a plan to integrate github and bitbucket to the workflow page

**Comment by bartleijssenaar** [comment]
@davidsemakula I also want to tackle this, this week is that doable?

**Comment by bartleijssenaar** [comment]
Can you create Issues for yourself and make a road map

**Comment by davidsemakula** [comment]
Yes ... will do
