### ISSUE TITLE
(EUR 40) Update Quality page

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#170]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Current quality page

## Expected behavior

We need to improve our quality page. In de .psd the design is shown. In the .psd there are some static element. These are static because the design and code are already available for either the current quality page or other pages on Tunga. Font size and color can be found in the .psd. If you can't find them reach out to Bart on Slack:

like to psd: https://drive.google.com/drive/u/1/folders/0B5csl9fqrXOCbnM5amsxZXVmaGM

![qualitypage](https://user-images.githubusercontent.com/12690878/28500944-08535966-6fd2-11e7-8b5e-a4e67b992a4e.jpg)

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by davidsemakula** [comment]
@waspa this is an update to this page https://tunga.io/quality
This is an update to this component https://github.com/tunga-io/tunga-web/blob/develop/src/routes/QualityPage.jsx
