### ISSUE TITLE
(EUR 30) Overlay 

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#171]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

not applicable 

## Expected behavior

![overlaytunga](https://user-images.githubusercontent.com/12690878/28500952-3f62e778-6fd2-11e7-9ee5-1e8cbfe3ddbd.jpg)

'Start hiring great developers?' 5.8 rem, font weight 700
'Free quote ....' 3 rem font weight 500
CTA 400X100 px 
'I'm not interested' 1.6rem font weight 400

Note: all content is centered & mobile friendly.
Icons: you can find them in the library 
X icon = font awesome
background: #ee1f54 opacity .9

This overlay should be triggered when the visitor hasn't moved his cursor for 45 secs

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by davidsemakula** [comment]
@bartleijssenaar can u add the conditions in which this should be triggered in the description?

**Comment by bartleijssenaar** [comment]
Added

**Comment by davidsemakula** [comment]
@waspa overlay should be added to this component https://github.com/tunga-io/tunga-web/blob/develop/src/routes/LandingPage.jsx

**Comment by davidsemakula** [comment]
@bartleijssenaar max-width of the text as well as margins are margins
cc @waspa (you can request missing info here as well)

**Comment by waspa** [comment]
@davidsemakula noted

**Comment by bartleijssenaar** [comment]
<img width="711" alt="screen shot 2017-07-24 at 10 00 34" src="https://user-images.githubusercontent.com/12690878/28513601-09ca5832-7057-11e7-9bab-dc131097f16f.png">

max width of the text is 960 px (based on a 1440px design)

Is this enough info @waspa @davidsemakula ?

**Comment by waspa** [comment]
@bartleijssenaar this is enough
