### ISSUE TITLE
(EUR 50) Tunga quiz (phase 1)

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#179]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Not applicable 

## Expected behavior

Currently, we have the wizard to gain information from Leads (potential clients). We want to test whether a quiz (sort of gamification) will boost the number of clicks and leads. Instead of starting the wizard you will start a quiz.

The quiz has 6 steps. 

<img width="720" alt="screen shot 2017-08-04 at 11 51 35" src="https://user-images.githubusercontent.com/12690878/28963992-53b39fc8-790b-11e7-9bf5-ee98abca8a5a.png">
<img width="898" alt="screen shot 2017-08-04 at 11 52 27" src="https://user-images.githubusercontent.com/12690878/28964023-6c85e100-790b-11e7-9198-dd458835143d.png">
<img width="898" alt="screen shot 2017-08-04 at 11 54 31" src="https://user-images.githubusercontent.com/12690878/28964101-bb28ae32-790b-11e7-8f94-cda5e5c6a81c.png">
<img width="896" alt="screen shot 2017-08-04 at 11 57 03" src="https://user-images.githubusercontent.com/12690878/28964208-1a7677d4-790c-11e7-9ac8-459500e93761.png">
<img width="896" alt="screen shot 2017-08-04 at 11 57 43" src="https://user-images.githubusercontent.com/12690878/28964226-286d0c22-790c-11e7-95b4-5eff484d61e0.png">
<img width="898" alt="screen shot 2017-08-04 at 11 58 07" src="https://user-images.githubusercontent.com/12690878/28964238-359d1f90-790c-11e7-85ad-806d95e64139.png">

They can be found is a PSD. The folder with all assets can be found here:
https://drive.google.com/drive/u/0/folders/0ByhMCVX4Ot9IWnkzdm8tMTFET2c

@davidsemakula can you add the icons to our library

**Comment by bartleijssenaar** [comment]
Phase 2 will come soon

**Comment by davidsemakula** [comment]
@bartleijssenaar do we already have zeplin for these?

**Comment by bartleijssenaar** [comment]
Yea I will upload one screen for the Spacing & padding (positioning). That is all you need right?

**Comment by davidsemakula** [comment]
@waspa icons have been added here https://tunga.io/icons/demo.html
You can always use this to check the icon names

**Comment by bartleijssenaar** [comment]
![quizscreenpx](https://user-images.githubusercontent.com/12690878/29076552-243e49e8-7c56-11e7-80c7-4a88b9a89916.jpg)
will this do? @davidsemakula 
Zeplin is acting up with this file.

**Comment by waspa** [comment]
@bartleijssenaar that will do.
@davidsemakula icons link noted
