### ISSUE TITLE
Chat improvements

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#180]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Current chat can be found on Tunga.io

## Expected behavior

Improve UX and UI

Currently, the visitor needs to click on the chat logo in the bottom right corner of the page to open the chat.

<img width="74" alt="screen shot 2017-08-04 at 16 19 51" src="https://user-images.githubusercontent.com/12690878/28972662-ce97665a-7930-11e7-9da0-fcacdaf0152c.png">

We want to chat to open when the user is longer than **10 seconds** on our page.

The following chat will pop up (don't pay attention to the text)

![chatsize2](https://user-images.githubusercontent.com/12690878/28972760-21307f78-7931-11e7-85a7-a27ed959512b.png)

In the header an intro text is presented that will displayed on 1 line:

"Hi there, we're are Tunga. How can we help?"

Below 3 pictures are displayed. 60px by 60px. They can be static for this release. 

Then the first message gets sent 2 seconds after the chat box opens (which is after *10* seconds).

Default this message is sent by David (but this is, of course, a bot message)

 "Hi, feel free to ask me anything."

When a visitor of Tunga asks a question in the chat bot, a second bot messages will be presented. This message comes with a form. 

<img width="355" alt="screen shot 2017-08-04 at 17 25 24" src="https://user-images.githubusercontent.com/12690878/28975332-ee1911a0-7939-11e7-8d31-17114e47ab7f.png">

We ask for the email of the user, to make sure we follow up with him/her and so we can target the user at a later moment. 

The user name that sends this message is "Tunga" and the message bar is almost the full width of the chat screen. 

When the user fills in their email the following message is displayed.

<img width="352" alt="screen shot 2017-08-04 at 17 35 12" src="https://user-images.githubusercontent.com/12690878/28975702-4e905ed4-793b-11e7-89dc-cb53e90d038c.png">

This screen disappears after 5 seconds.

Then when someone from Tunga answers the question via Slack the correct picture should be showing (based on their Slack picture) and of course the correct name.

PSD file can be found here:

https://drive.google.com/drive/u/0/folders/0ByhMCVX4Ot9IV3lDMnRVU2s5ZTA

**Comment by davidsemakula** [comment]
![Screen Shot 2017-08-10 at 07.45.24.png](https://images.zenhubusercontent.com/5974812561b4ca3b0a755d89/d8b9ae23-3883-42ef-be38-6169a9274766)

**Comment by davidsemakula** [comment]
@bartleijssenaar is it possible to get this in Zeplin?
Also are we killing this form
![Screen Shot 2017-08-10 at 07.48.26.png](https://images.zenhubusercontent.com/5974812561b4ca3b0a755d89/4ed37b9d-ee7a-445a-bc66-2e5ad54e8b54)

I'm in favor of killing it
However, this means the new widget that requests for the email should request for the name as well.

**Comment by bartleijssenaar** [comment]
Yes, will upload it to zeppelin.

Yes, we are killing it. We can include the first name as well (at the start). Other big org. like intercom, dont do it tho... 

Let me think of something smart and upload that here.

**Comment by bartleijssenaar** [comment]
Let's skip first names. The chat file is in Zeplin. @davidsemakula

**Comment by bartleijssenaar** [comment]
You will need the PSD file tho to see the logic of the email address. See also this screen recording http://recordit.co/OkO8ZJ2oRh
