### ISSUE TITLE
Mobile friendly landing section 

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#184]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Our current landing page is mobile friendly, except the first landing page section. 

## Expected behavior

A mobile friendlier design for the first section of the landing page on mobile. The other section can remain the same.

The design can be found in Zeplin. 

![round100px](https://user-images.githubusercontent.com/12690878/29264205-63ce88fe-80dc-11e7-86ac-81edb989aab1.png)

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by bartleijssenaar** [comment]
@davidsemakula do you need a svg of the hamburger menu, or can you just pick one from font awesome or any other library?

**Comment by davidsemakula** [comment]
@bartleijssenaar font awesome will do

**Comment by davidsemakula** [comment]
@waspa here's the design for this ... https://app.zeplin.io/project/5977533d141d9d52ca3e175d/screen/59915c8d861c27a04150ed5e

Be sure to change the logo image and position on mobile (hide existing one) and change the menu indicator, other things about the menu should already be in place.

**Comment by waspa** [comment]
@davidsemakula , this has been noted
