### ISSUE TITLE
Quiz 2 backend

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#211]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Expected behavior

https://docs.google.com/document/d/1db-8fRaEyL61RWHOCy-GdDOhJ0odABDh5m5LAmLHO9U/edit

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by davidsemakula** [comment]
@bryanlamtoo please upload the flowchart here

**Comment by davidsemakula** [comment]
@bryanlamtoo still waiting for that flowchart

**Comment by bryanlamtoo** [comment]
![page 1](https://user-images.githubusercontent.com/5203572/33197106-720c5e1a-d0f4-11e7-9f80-a2c2068d699a.png)
![page 2](https://user-images.githubusercontent.com/5203572/33197107-72407006-d0f4-11e7-820d-7b7a025ee2ce.png)
