### ISSUE TITLE
(EUR 60) New wizard steps plus update designs

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#212]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Current we have a lot of (unnecessary steps)

## Expected behavior

You can view the new steps in these documents:

Task flow questions: https://docs.google.com/document/d/1b0UbUAOXZz_BiF2pAJ9RzbM9B8vrYxFkcl6pjOGLV_Q/edit
Project flow questions:
https://docs.google.com/document/d/14fX_7Ah6l211_1vb4tT14jRSQhaaglPgztN67P5MGJs/edit

Design screens can be found in zeplin filter = wizard. 

The basic logic of the design: 3 options (there are exceptions) 
1) big text box
2) small text box
3) multiple choice 

Note:
1. The content is always centred. When it is in the wizard it is truly centred when it is on the platform (when logged in) it is centred between the right edge of the navbar (on the left side) and the other edge of the screen (right side)
2. In the designs the focus the put on the new assets. e.g. navbar and sidebar not worked out in detail. 

More on this in the documents. 

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by davidsemakula** [comment]
@bryanlamtoo the text changes in the attached docs have not been processed
