### ISSUE TITLE
(EUR 80) Message page update

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#213]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Can be found on https://tunga.io/conversation/start

## Expected behavior

Designs can be found op Zeplin. Filter = Message. Extra comments can be found in Zeplin 

## What is the motivation / use case for changing the behavior?

In line with new look of Tunga

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

**Comment by davidsemakula** [comment]
@bryanlamtoo please process the info in the Zeplin files, add it to the description and add links to Zeplin files for the devs

**Comment by bryanlamtoo** [comment]
https://app.zeplin.io/project/5977533d141d9d52ca3e175d/dashboard?tag=Message

**Comment by davidsemakula** [comment]
@adelekand please implement the mobile changes in the Zeplin as well

**Comment by davidsemakula** [comment]
@adelekand mobile responsiveness is still off, please review Zeplin files and test/ inspect on mobile devices

**Comment by adelekand** [comment]
OK, would work on that today
