### ISSUE TITLE
(EUR 20) Pricing page update (mobile)

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#215]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

Please check on your mobile tunga.io/pricing

## Expected behavior

Designs can be found in Zeplin. Filter = pricing.

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by bartleijssenaar** [comment]
![mobilepricing](https://user-images.githubusercontent.com/12690878/31665665-e80612b4-b349-11e7-8f8c-5ccc3ef71bd6.jpg)

**Comment by davidsemakula** [comment]
@bryanlamtoo this one is up
