### ISSUE TITLE
(EUR 120) Add activity notifications to top bar

### ISSUE THREAD

**Issue by davidsemakula** [tunga-io/tunga-web#237]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[x] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Expected behavior

Similar to notification feed on Youtube, read notifications from the `/api/activity` endpoint
Filtered by user `?user=<user_id>`

Focus mainly only the `activity_type`s and `action`s already handled in this switch block of the `ActivityList` component https://github.com/tunga-io/tunga-web/blob/master/src/components/ActivityList.jsx#L69-L392

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by bryanlamtoo** [comment]
Use the following end-point */api/activity/*
