### ISSUE TITLE
Redesign Log in and Sign up (join) 

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#24]
Design will follow

PLEDGE = 30$

**Comment by bartleijssenaar** [comment]
![createyouraccount2](https://cloud.githubusercontent.com/assets/12690878/15926357/eba699be-2e3b-11e6-9e83-6476001a7e3c.jpg)

![create your account1](https://cloud.githubusercontent.com/assets/12690878/15926358/ebaeea56-2e3b-11e6-80f0-cb51fc949b24.jpg)

Jonathan, please ping me on slack about this

**Comment by bartleijssenaar** [comment]
I also have an ai. file

**Comment by jonathanzerox** [comment]
finished implementing the design in html and css, and also converted the templates to react...

**Comment by bartleijssenaar** [comment]
Jonathan, nice work up till now. Only the fields must have an opacity of .8. also the padding is a little too big between the fields as well as the padding between the logo's and 'or'.

**Comment by bartleijssenaar** [comment]
RE 1st screen for creating an account

please remove the white font shadow
