### ISSUE TITLE
Should be able to remove a developer from a given project

### ISSUE THREAD

**Issue by bryanlamtoo** [tunga-io/tunga-web#244]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[x] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Current behavior

Its not possible to remove a developer already assigned to a given project. 

## Expected behavior

+Should be able to revoke any invitation to join a project
+Update the project team by removing developers when necessary

## What is the motivation / use case for changing the behavior?

Sometimes a developer may leave the project or may need to be replaced with another and they no longer need to submit reports or be part of the project at all

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by bartleijssenaar** [comment]
@davidsemakula Is this already implemented. I see you removed the assignment.

**Comment by davidsemakula** [comment]
Wanted to change the scope, I'll create a new issue
