### ISSUE TITLE
(EUR 120) Creating internal blog posts with Draft-js widgets

### ISSUE THREAD

**Issue by davidsemakula** [tunga-io/tunga-web#250]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[x] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Current behavior

Blog posts are currently externally hosted on medium

## Expected behavior

Create a rich text editor for writing blog posts from Tunga
Created blog posts will be stored at the `api/blog-post` endpoint
Necessary Actions and Reducers need to be created
Views for creating, editing and listing need to be created with the paths
- List: `/blog/`
- Create: `/blog/new`
- Edit: `/blog/:slug`

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by davidsemakula** [comment]
@raheemazeezabiodun changed
Edit: `/blog/:id`
to
Edit: `/blog/:slug`

**Comment by davidsemakula** [comment]
@raheemazeezabiodun please convert list view to a table format
Can you also add support for file uploads it's a key feature for a Rich Text Editor meant to compose blogs

**Comment by raheemazeezabiodun** [comment]
Okay, i will do that
