### ISSUE TITLE
image doesn't load on PHP landing page

### ISSUE THREAD

**Issue by espruyt** [tunga-io/tunga-web#263]
## I'm submitting a ...
<pre><code>
[x] Bug report
[ ] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Current behavior
After loading the PHP landing page between question 4 and 5 there is an image that doesn't load. See screenshot here:
https://images.zenhubusercontent.com/59b93bc1b0222d5de4779254/c281c04b-bfac-4471-a14a-e9d563e6d31a

Not sure what the image is/should be about as I checked some other landing pages (javascript, c-sharp) and they don't have an image in this section at all.

## Expected behavior
Image either is loaded or there is no placeholder for an image.

## Minimal instructions for reproducing the problem (optional for feature requests)
Just paste https://tunga.io/PHP/ in your browser and see for yourself

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [x ] Linux Ubuntu 17.10
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [x] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Requested Delivery Date: dd/MMM/YYYY
ASAP
</code></pre>

**Comment by espruyt** [comment]
@bryanlamtoo is it possible to include this bug fix in the current sprint?

**Comment by davidsemakula** [comment]
@espruyt @bryanlamtoo I'll take this one an put an image today

**Comment by espruyt** [comment]
great thanks

**Comment by davidsemakula** [comment]
@espruyt just killing the image for now, no idea which one it's supposed to be
