### ISSUE TITLE
Feature Butterfly Works more prominently

### ISSUE THREAD

**Issue by espruyt** [tunga-io/tunga-web#266]
## I'm submitting a ...
<pre><code>
[ ] Bug report 
[ ] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Enhancement
</code></pre>

## Current behavior

I got a message from Butterfly Works that they would like to have their name+logo more prominently features on our website. I have no problem with that, so let's see how we can make them happy.

## Expected behavior

- on the our story page Butterfly Works is mentioned in the second sentence. Please include a hyperlink to http://web.butterflyworks.org/
- please include a butterfly works logo somewhere in the vicinity of that section
- please include in the footer the text: "a butterfly works initiative" with a link to http://web.butterflyworks.org/

## Requested Delivery Date:
ASAP
This is quite urgent as this is a sensitive matter to our partners.

**Comment by remo4sam** [comment]
Added a few changes for this.
This is what it could look like.

<img width="954" alt="screen shot 2018-01-25 at 12 22 31" src="https://user-images.githubusercontent.com/449456/35380553-a2bba14a-01ca-11e8-906e-12032de3019c.png">
<img width="1373" alt="screen shot 2018-01-25 at 12 22 40" src="https://user-images.githubusercontent.com/449456/35380678-105165be-01cb-11e8-9edf-71f397769565.png">

Hope this is fine? Working with David to merge it in and how the deploy to testing hows

**Comment by remo4sam** [comment]
<img width="1552" alt="screen shot 2018-01-25 at 12 47 50" src="https://user-images.githubusercontent.com/449456/35381746-5222a05e-01ce-11e8-9e05-a91e252a6b45.png">

**Comment by espruyt** [comment]
looks good! @remo4sam
