### ISSUE TITLE
Marking Invoice as Paid (60 EUR)

### ISSUE THREAD

**Issue by remo4sam** [tunga-io/tunga-web#271]
This task includes the following mini tasks:
- Add a button Mark as Paid
- Once clicked throw up a confirm popup dialog asking “Please confirm is this invoice is indeed paid”
- On accepting on the dialog, this trigger payment to the developers in the payout via payoneer 

![Payment overview option 2.jpg](https://images.zenhubusercontent.com/5a65f2e54b5806bc2bc3ba5e/f152296c-860d-4df3-b8c2-1102e15b881e)

**Comment by bartleijssenaar** [comment]
![example pop up](https://user-images.githubusercontent.com/12690878/36528652-2036a8e4-17b6-11e8-84bf-5dd940b7e9db.jpg)

This is an example of a pop up
