### ISSUE TITLE
Request Payment button

### ISSUE THREAD

**Issue by calistus** [tunga-io/tunga-web#285]
Add a button that will enable developers to request for payment from their dashboard. 

When a task sprint is completed and approved, a developer should be able to request for his  payment from the payment section if the dashboard.

When this button is clicked. The developer has to select the project and the sprint he wants to get paid for. Then a notification will be sent to Tunga admin about this request.

**Comment by bartleijssenaar** [comment]
This will be in the payment overview of the developers, correct @calistus  ?

**Comment by calistus** [comment]
Yes.

**Comment by bartleijssenaar** [comment]
@remo4sam can you make an estimate of the hours?

**Comment by davidsemakula** [comment]
@bartleijssenaar @calistus do we still need this in the Tunga?
re-open or start the discussion on Slack in #product in you think we do
