### ISSUE TITLE
New landing page

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#310]
The landing page will have a new fresh look. 

The UI can be found in Zeplin. Also, see the comments in Zeplin.

The graphic elements can be found here: https://drive.google.com/drive/folders/1WUUEnFNVqxWv6nIl9Z_bLzc1mXAPCIkN

text
https://docs.google.com/document/d/1h6MokIQaLCR6-_9hBaUzjZWVbeDeTt_MWtysrrObWF0/edit

**Comment by remo4sam** [comment]
New landing page #310 - 2 hours

**Comment by bartleijssenaar** [comment]
@davidsemakula, hereby the list of things that are still pending.

In the first section (first 800px)

- The H1 should have a font size of 5rem and a font weight of 400. 
- The subheader should be font weight 300. 
- All three elements (h1, subheader, and btn should be more to the left) There is roughly 210 px between the left edge of the screen and the start of those elements
- The text in the 3 grey boxes are wrongly aligned, please review the design in 
- The read more text (hyperlink) is missing in the boxes. We can add the hyperlinks later, bc I will create them with the skill page 'creator' from the admin environment.
- The Header in the boxes are in line with my design but on 'web' it looks different. When we change the font size to 22px and font weight to 500, it comes closes to the design.

Hybrid issue for first and second section:

- The picture on the second section and the third box should be aligned, this is currently not the case. Also the picture is incorrect. In the drive folder (see issue) you can find the correct picture.

2nd section:

-Padding between the header and the boxes are way off. See design in Zeplin, this should be 80px.
- Header on the 2nd section is incorrect. Its should be 2.4rem, 500 font weight
- the content is more centred than it should be. There is roughly 210 px between the left edge of the screen and the start of those elements
- The text is not the latest text, see the latest text in the drive folder
- btn is missing

3rd section

- The background is grey instead of white
- Padding start 3rd section and header is off. Should be 80px
- The header is off (styling is mentioned above)
-  padding between line and subheader is off. 
- padding between subheader and icons is off.
- In conclusing almost off paddings are off. Please review the padding in Zelpin. 
- In the text under the icon there should be a bolder header text. This is missing
- The total height of this section is 560 px, this is currently not the case. 

4th section (picture)

- I don't know what is going on with the text, but this is way off. 

5th section (media section)

- padding is way off

6th section  (testimonials)

- Padding between start section and header is off.
- styling header is off
- padding between header and line is off. 
- The centre box should have more width. This will mean that boxes on the side will be smaller. David, can you see what works best. I trust your judgement.
- Let's lower the speeds of this slider.  


7th Section (supported by)

- Padding is off 
- Header styling is off

8th section

- Padding is off between start section and header\
- Header styling is off
- Mobile image should be more to the centre. Please align the alignment (pun? hehe) with the design. 
- btn is missing

9th section:

-Padding between the header and line is off. 
- The text is strangely aligned to the left. In the design, this is not the case
- Btns are not alligned
- Form boxes do not have shadow
- btns do not have shadows

Footer:

- The footer is the old one. I believe Amos or Remo have changed the footer already but it does not show here.
