### ISSUE TITLE
Friend of Tunga rules page (10EUR)

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#313]
URL: tunga.io/friend-of-tunga-details

This is a very easy page!

See Zeplin for the design.

Here you can find the image for this page:  https://drive.google.com/drive/folders/1cysqOOYmkDiNAnabKbldhQN-69ElaksH

This is the text:

How does your referral program work?

Tunga is a commercial company (Dutch B.V.) with a registered branch office in Uganda. As any commercial company we want to run a healthy profit, but next to that we have an explicit social mission. Tunga was founded to create opportunities for African youths, in particular by creating job opportunities in the tech sector.

Do you support this mission? Then you help us directly as a company by referring leads to us. On top of that, for each referral that becomes a paying customer, we donate 5% up to EUR1,000 to Bits Academy, a network of schools that gives free tech education to African youths from less privileged backgrounds. We have come up with this mechanism to improve access to tech jobs for those youths who need it most so that we can do more to achieve our mission.

- You can refer leads to us by putting us in cc in a referral e-mail.

- On the program page, we have created some tools to make this easier for you.

- If you have referred a lead to use via other channels, please send us an e-mail at bart@tunga.io and we’ll make sure it is properly administered.

- Each referral lead is formally tagged as a ‘Referral’ in our CRM system.

- For each referral that becomes a paying customer, Tunga commits to supporting Bits Academy, which provides free tech education to African youths.

- Bits Academy, for now, is run as a project by the Butterfly Works Foundation (Netherlands), who will administer any donations.

- At the end of each calendar year, we calculate the applicable donation by multiplying the total received invoice amounts (ex VAT) from that client with 5%.

- The maximum donation per referral is set at EUR1,000.

- For example, if the donation amount for a referral is 600 in year 1, 500 in year 2 and 700 in year 3, then 600 is donated in year 1, 400 in year 2 and 0 in years (and onwards, because the maximum amount has been reached).

- The sum of donations for a calendar year is transferred to the Bits Academy budget account at Butterfly Works within 2 months of the start of the next calendar year.

- Tunga will discuss with Bits Academy before the end of each calendar year if and for what the donation amount will be earmarked.

- We reserve the right to remove access to the referral program or to refuse a reward if we suspect cheating or any activity we determine as abusive (for example, by inviting yourself, fictitious people, or already existing users) or damaging of the Tunga brand (for example, in connection with sexually explicit, discriminatory or illegal content).

- We reserve the right to modify the referral offer at any time. By continuing to invite friends after an update to the terms, you are indicating that you are accepting them.

**Comment by remo4sam** [comment]
Friend of Tunga rules page #313 - 1 hour

**Comment by bartleijssenaar** [comment]
http://sandbox.tunga.io/friends-of-tunga-rules

Pending issues:

- The picture should be 300 pix instead of 250 px
- H1 font-weight = 500. 

Content area

- Padding between the picture and the text is off, this should be 80 px
- The should be another empty line between the bold headers in the text and the 'normal' text
- The normal text (p) should have the same styling. 14 px or 1.4rem
- padding between the text and footer should be 80px as well.

**Comment by Wamosrich** [comment]
Rectified
