### ISSUE TITLE
Our Story page text upload + minor UI Changes (10 EUR)

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#314]
The updated design can be found in Zeplin 

The updated text and image can be found here: https://drive.google.com/drive/u/0/folders/12kFp-AMCcZpDj5TbqjfWCi4tT3FP2kJP

**Comment by bartleijssenaar** [comment]
@remo4sam how many hours for this one?

**Comment by Wamosrich** [comment]
1 hour

**Comment by bartleijssenaar** [comment]
@Wamosrich great

**Comment by bartleijssenaar** [comment]
Pending issues:

- The first image is incorrect. Please find the correct picture in the drive folder: https://drive.google.com/drive/u/0/folders/12kFp-AMCcZpDj5TbqjfWCi4tT3FP2kJP
- Because of this the padding seems off. 
- The H1 should have a font size of 5rem and a font weight of 400.
- The subheader and btn should be font weight 300.
- Text btn = schedule a call 

Content area:
- the headers of the content should have font-weight 
- The content text should have the same styling as the landing page and skill pages @davidsemakula 
- the padding between the sections, header, lines and text are off. 
It should look like this: (please review the padding in Zeplin)
![screen shot 2018-04-04 at 18 51 21](https://user-images.githubusercontent.com/12690878/38322859-eb9f71aa-383b-11e8-8888-d85566071075.png)
In the section: Our Mission: 21st Century Jobs for African Youths the logo's of our sponsors are missing.
