### ISSUE TITLE
Quality page (Minor UI Changes) (10 EUR)

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#315]
Please see design and comments in Zeplin

Only the subheader has an updated text: 

We thoroughly select the brightest developers from the African continent. Tunga nourishes and constantly improve our community of developers by providing them with the tools and guidance they need to be even more successful.

Image can be found here: https://drive.google.com/drive/u/0/folders/1WgUlAM5YIPPQboEJXurAQJeLkwUBMF9I

**Comment by remo4sam** [comment]
Quality page (Minor UI Changes) #315 - 1 hour

**Comment by bartleijssenaar** [comment]
Pending issues:

- The first image is incorrect. Please find the correct picture in the drive folder: https://drive.google.com/drive/u/0/folders/1WgUlAM5YIPPQboEJXurAQJeLkwUBMF9I
- Because of this the padding seems off. 
- The H1 should have a font size of 5rem and a font weight of 400.
- The subheader and btn should be font weight 300.
- Text btn = schedule a call 

Content:

- the styling of the header is incorrect. the font-size should be 2.4rem (24px) and the font weight 500
- the font weight of the headers like 'screening portfolio' and 'Soft skills' should be 500.
