### ISSUE TITLE
Additional option to extend deadline on a project or sprint.

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#316]
The will be btn in the sprint meeting page for PMs and developers (if there is no PM) to extend the deadline.

This will look like this:
![extend deadline1](https://user-images.githubusercontent.com/12690878/37668015-b9b0b9c6-2c63-11e8-9f61-5abb328d6a3c.jpg)

When the btn is clicked a pop up appear. This btn will display the following form:

![extend deadline2](https://user-images.githubusercontent.com/12690878/37668131-00687d9a-2c64-11e8-8490-21b0c72196f5.jpg)

When the form is sent to the client, the client and Tunga admin users get the following e-mail. 

<img width="706" alt="screen shot 2018-03-20 at 17 33 09" src="https://user-images.githubusercontent.com/12690878/37668443-d26a9490-2c64-11e8-898c-4597be854dc7.png">

**Comment by espruyt** [comment]
@bartleijssenaar 
> The will be btn in the sprint meeting page
I assume you mean: There will be a btn in the spring PLANNING page
I also assume that if the sprints have already been planned, that this page will display a list of sprints that have been planned
Then the behind each deadline there can be a 'delay deadline' button.

Questions: should there be an option 'affects later sprints'. if checked, will it automatically change later sprint deadlines accordingly? or should each sprint deadline be adjusted manually? if yes, then ideally only 1 e-mail with all the changes instead of separate e-mails, because this will confuse the client

**Comment by espruyt** [comment]
@bartleijssenaar 
Re popup box/reasons for deadline
I would prefer this to be a checklist, with predefined reasons: technical blocker, client dependency, third party failure (Tunga responsibility), third part failure (client responsibility), other...
and then a text box in which they can elaborate/explain in more detail

[re 'client dependency': as we will report this to the client I have tried to find a neutral term. if you have a better option then please. In any case, this refers to clients not being in time with providing us with assets/resources/replies/etc. Perhaps in the checklist this can be explained a little bit as long as it is not forwarded to the client]

**Comment by espruyt** [comment]
Re e-mail: good e-mail. Possibly needs to change if multiple deadlines are effected simultaneously (see comment above)

**Comment by davidsemakula** [comment]
@bartleijssenaar needs to be reconciled with current design of "Planning" section in Invision which doesn't seem to have Sprint planning functionality from the platform

**Comment by bartleijssenaar** [comment]
@davidsemakula It's there already. Tho, I did not write up the mechanism we need to create if multiple deadline are pushed/changed.

**Comment by bartleijssenaar** [comment]
Admin_projects_planning_changemilestone in admin

**Comment by davidsemakula** [comment]
@bartleijssenaar it's more Sprint creation ![Sprint creation](https://user-images.githubusercontent.com/12690878/37668015-b9b0b9c6-2c63-11e8-9f61-5abb328d6a3c.jpg)

than the extend deadline functionality (which is what u mentioned)

Right now the planning section only has ability to create milestones (title, due_at), not sprints (i.e picture above) which are more detailed.

Reconciliation may mean finally figuring out how to resolve the confusion between the two as platform.

**Comment by bartleijssenaar** [comment]
Indeed create a milestone but also edit a milestone (extending). But I will make it more explicit in the design. Would that solve it?

**Comment by davidsemakula** [comment]
@bartleijssenaar I'm closing this for now, we may need to discuss again how and if we need to re-introduce detailed sprint planning as part of the core platform
See my comment above 
https://github.com/tunga-io/tunga-web/issues/316#issuecomment-391618826
