### ISSUE TITLE
New pricing page (UI Changes) (10 EUR)

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#317]
The pricing page will get a new look which will be more simplistic. 

The Design can be found in Zeplin
The UI elements can be found here: https://drive.google.com/drive/u/0/folders/15WkLCHOovN0EvUjb2bRL-2oLgPwgvZQC
The text can be found here: 
https://docs.google.com/document/d/1Fzu7NlsFZ2830TW9iAIOvVcxQxiURaGwNHEhbZzvnOM/edit

**Comment by remo4sam** [comment]
New pricing page (UI Changes) #317 - 1 hours

**Comment by bartleijssenaar** [comment]
Pending issues:

- The first image is incorrect. Please find the correct picture in the drive folder: https://drive.google.com/drive/u/0/folders/15WkLCHOovN0EvUjb2bRL-2oLgPwgvZQC
- Because of this the padding seems off.
- The H1 should have a font size of 5rem and a font weight of 400.
- The subheader and btn should be font weight 300.
- Text btn = schedule a call

Content area:

- The padding between the picture (1st section) and the 3 boxes are off. 
- please use the shadow styling of the developer boxes. 
- Header of the boxes have a font-weight of 500
- The padding between the boxes is 20 px instead of 10 px
- Styling of the text in the boxes
What has been created:
![screen shot 2018-04-04 at 20 05 48](https://user-images.githubusercontent.com/12690878/38325572-a8ce0208-3843-11e8-94ce-fedd96a9f18e.png)
vs
![screen shot 2018-04-04 at 20 06 47](https://user-images.githubusercontent.com/12690878/38325602-bc1686c8-3843-11e8-81ea-4fc688b86c06.png)
Please work more carefully! @Wamosrich 
Also the schedule a call to find out more text should have hyperlink to tunga.io/call
- Padding between the boxes and the 'schedule call' btn should be 80px
- Padding between 'schedule call' btn and footer should be 80px
- Text btn is incorrect. 
- Btn should have a shadow
