### ISSUE TITLE
Schedule hours developers on platform

### ISSUE THREAD

**Issue by Domieck** [tunga-io/tunga-web#322]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Current behavior

N.A.

## Expected behavior

There's a need for scheduling hours of developers on project. This involves scheduling ahead (e.g. every Sunday), so that the admins & PM's have insight into the availability of the developers. 

Ideally, the feature would present an agenda that allows filtering on a certain developer (e.g. Remo). Once you select Remo, you get his agenda for the coming week, Monday to Friday. This agenda could show how Remo is for instance occupied on Tuesday from 9 AM - 12 PM CET with Project X. However, when it shows availability from 12 PM onwards, either the PM or Admin should have a functionality to schedule time for a project, e.g. Project B. 

At the same time, this agenda should trigger data per developer: how many hours in total was scheduled, how many per project or other activities, etc.

## Requested Delivery Date (feature requests only):
April 17, 2018

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

@bartleijssenaar Can you take it from here?

**Comment by Domieck** [comment]
And improve/add to the description if necessary

**Comment by davidsemakula** [comment]
@Domieck  do we still need this in the Tunga?  
re-open or start the discussion on Slack in #product if you think we do
