### ISSUE TITLE
Add logos+links of publications to homepage

### ISSUE THREAD

**Issue by espruyt** [tunga-io/tunga-web#324]
## I'm submitting a ...

[ ] Bug report 
[ ] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Enhancement

## Current behavior
The displayed logos with reference to publications about Tunga are outdated. We need to add a few recent ones.

## Expected behavior
Please add the following publications (in order of priority):
https://www.telegraaf.nl/nieuws/1876342/podium-voor-afrikaans-it-talent
https://www.sprout.nl/artikel/startup-van-de-week/deze-nederlandse-startup-laat-websites-en-apps-bouwen-door-afrikaanse
https://www.gsma.com/mobilefordevelopment/programme/ecosystem-accelerator/three-takeaways-africa-technology-business-forum/
https://www.social-enterprise.nl/wie-doen-het/tunga/
https://soundcloud.com/boostznl/10-van-idee-tot-app-hoe-doe-je-dat-zonder-it-kennis-en-groot-budget
(find logo here https://www.google.nl/search?q=logo+boostz.nl&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjyyt6y9tLaAhWGW8AKHbvMDIkQ_AUICigB&biw=1853&bih=934#imgrc=Sd4FAObYO6yQqM:
)
https://socreatie.nl/ernesto-spruyt-afrikaanse-programmeurs-inhuren-via-tunga/

Optional:
http://blog.sinzer.org/news/tech-for-good-how-much-impact-is-tungas-impact-sourcing-creating
https://www.kukua.cc/hiring-software-developers-in-africa/
https://riseafricarise.com/tunga-ernesto-spruyt/

## Requested Delivery Date (feature requests only):
01/05/2018

**Comment by espruyt** [comment]
@bartleijssenaar @davidsemakula @remo4sam forgot to ask this morning: could someone pls enlighten me as to the ETA of this issue? many thanks

**Comment by bartleijssenaar** [comment]
Hi @remo4sam can you pick up this issue? The logo's are here: https://drive.google.com/drive/u/0/folders/1e6ST5S0yMqaDpzjJSW6ws9EniwLoete-

Could you also from the existing logo/links now on production delete `Spend matters`?

**Comment by remo4sam** [comment]
@bartleijssenaar @espruyt This is done and deployed.
