### ISSUE TITLE
Create Tunga CSS Library

### ISSUE THREAD

**Issue by davidsemakula** [tunga-io/tunga-web#330]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[x] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Current behavior

CSS for Tunga widgets is not very organized in a structured library leading different contributors to redefine the same UI widgets.

## Expected behavior

- Create a library of css for Tunga widgets which will be re-used by all contributors.
- The library css should extend bootstrap 4 components to avoid reinventing the wheel and this should be it's only dependency. As such current css files on Tunga should not be dependencies (styles may be copied however).
- [Sass](https://sass-lang.com/) (.scss format) CSS pre-compiler should used to allow imports of source sass files from bootstrap
- [Zeplin link here] page should be reproduced to showcase created css.
- Pull request should be pointed at https://github.com/tunga-io/tunga-ui

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by kantologist** [comment]
Since the library is in a different repository, would be imported like an npm package to the main project?
