### ISSUE TITLE
(EUR 240) Create Profile, Company Profile, Company Details and Experience sections of the setting page

### ISSUE THREAD

**Issue by davidsemakula** [tunga-io/tunga-web#335]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[x] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Expected behavior

All components are already connected to the redux store and receive `Auth` and `Profile` as props.
Find current user's object at `Auth.user`
Additionally all components receive `ProfileActions` as a prop

- Profile:
https://app.zeplin.io/project/5977533d141d9d52ca3e175d/screen/5b17f444280d391462a7f0b3
Implement at https://github.com/tunga-io/tunga-web/blob/develop/src/components/settings/Profile.jsx
Save with `ProfileActions.updateProfile`

- Experience:
https://app.zeplin.io/project/5977533d141d9d52ca3e175d/screen/5b17f445e20029e35d16fb39
https://app.zeplin.io/project/5977533d141d9d52ca3e175d/screen/5b1a4e848b2f46b434d155bf
https://app.zeplin.io/project/5977533d141d9d52ca3e175d/screen/5b1a4e845f280dcc6b358573

Implement at https://github.com/tunga-io/tunga-web/blob/develop/src/components/settings/Experience.jsx
Save skills with Save with ProfileActions.updateProfile
and work and education with save with `ProfileActions.updateWork` and `ProfileActions.createWork` and `ProfileActions.updateEducation` or `ProfileActions.createEducation` respectively
`ProfileActions.updateWork` or `ProfileActions.createWork`

- Company Profile
https://app.zeplin.io/project/5977533d141d9d52ca3e175d/screen/5b1a8e11cc5680ae11868f3e
Implement at https://github.com/tunga-io/tunga-web/blob/develop/src/components/settings/CompanyProfile.jsx
Save with `ProfileActions.updateCompany`

- Company Details
https://app.zeplin.io/project/5977533d141d9d52ca3e175d/screen/5b1a8e12a1df3b157b2010c4
Implement at https://github.com/tunga-io/tunga-web/blob/develop/src/components/settings/CompanyDetails.jsx
Save with `ProfileActions.updateCompany`

Successful saves will lead to `Profile.isSaved.profile`, `Profile.isSaved.work`, `Profile.isSaved.education` and `Profile.isSaved.company` changing to true for respective save methods.
While errors will lead to `Profile.errors.profile`, `Profile.errors.work`, `Profile.errors.education` and `Profile.errors.company` contained a dictionary of errors for each for respective save methods.

Use `ProfileActions.getCountries` to get a list of countries access and access the list at `Profile.countries`

Refer to the Data dictionary and API explorer for the appropriate field names to use for saving data and parsing errors.

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by raheemazeezabiodun** [comment]
Am in for it
