### ISSUE TITLE
(EUR 80) Create project form

### ISSUE THREAD

**Issue by davidsemakula** [tunga-io/tunga-web#339]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[x] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Expected behavior

https://github.com/tunga-io/tunga-web/blob/develop/src/components/projects/ProjectForm.jsx
Component is connected to redux store and receives `project`, `onCreate`, `isSaving`, `isSaved` and `errors` props.
Save with onCreate, pass in a [Project](http://resources.tunga.io/docs/data-dictionary#idProject) object.

isSaving and isSaved track current status of save action

project will contain the save `Project` object on successful save and isSaved with change from false to true.

`skills` and `documents` should saved as attributes on the project object passed to onCreate

`skills`: an array of [Skill](http://resources.tunga.io/docs/data-dictionary#idSkill) objects `[{"name": "React.js"}, {"name": "Django"}]`
`documents`: an array of [Document](http://resources.tunga.io/docs/data-dictionary#idDocument) objects

Redirect to `/projects/<project_id>` with `history.push` after successful save

Designs:
https://app.zeplin.io/project/5977533d141d9d52ca3e175d/dashboard?tag=add%20new%20project

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by ziwer1** [comment]
@david I'll take this

**Comment by davidsemakula** [comment]
@ziwer1 make some changes to the instructions, be sure to read those and all pull the latest code
