### ISSUE TITLE
Improvement of developers/PO cards

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#34]
New design for developers and PO cards (Tribe page)

Will be uploaded to the drive soon

**Comment by jonathanzerox** [comment]
Hello bart do you have the design/mockup for the cards so i can start working on it right away?

**Comment by bartleijssenaar** [comment]
I will have it for you tomorrow

**Comment by bartleijssenaar** [comment]
see slack for the design. lets talk there!
