### ISSUE TITLE
(EUR 80) Create Documentation component for project workflow page

### ISSUE THREAD

**Issue by davidsemakula** [tunga-io/tunga-web#343]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[x] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Expected behavior

Designs:
https://app.zeplin.io/project/5977533d141d9d52ca3e175d/screen/5b1a596be02db465224afbe9

Docs component can be found here
https://github.com/tunga-io/tunga-web/blob/develop/src/components/projects/Docs.jsx
And receives `project` and `ProjectActions` props

`project` has an array of  [Document](http://resources.tunga.io/docs/data-dictionary#idDocument) objects in `documents` key. 

Use the `download_url` readonly key of document objects to render links.

When creating documents on of `file` or `url` must be set.

Create, Update and Delete single document objects
```JS
ProjectActions.createDocument({...})
```
```JS
ProjectActions.updateDocument(id, {...})
``` 
```JS
ProjectActions.deleteDocument(id)
``` 

And bulk create with 
```JS
ProjectActions.updateProject(<project_id>, {documents: [{...}]})
``` 
the project id can be skipped for the document object in this case

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by davidsemakula** [comment]
@ziwer1 u can take this one over

**Comment by ziwer1** [comment]
@davidsemakula sure.
what is the second argument to `ProjectActions.deleteDocument(id, {...})` is it the document being deleted?

**Comment by davidsemakula** [comment]
@ziwer1 mistake, issue details updated
