### ISSUE TITLE
Join Tunga page

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#350]
Goal: to have a page on our website where developers that want to join Tunga can sign up. 

The design and further comments can be found on Zeplin:
Text can be found here: https://docs.google.com/document/d/1Wf1_gsxApvE7iNOE9p4H20vtSEra6R3PIJJQIqBwqow/edit

Email send module (the right element on the page):

3 forms:
1. placeholder: Your name
2. placeholder: Your email address 
3. placeholder: Type your motivation here

Upload function for CV

Send btn

The form should be sent to domieck@tunga.io
The template for the email will be uploaded to Mandrill @davidsemakula 

@davidsemakula let me know how we can tackle the attachment function.

Design:
![join tunga page](https://user-images.githubusercontent.com/12690878/41042439-fa3d73be-69a1-11e8-8938-b551cb59c625.jpg)

**Comment by davidsemakula** [comment]
@bartleijssenaar upload processing is straight forward, we'll add it as an attachment to the subsequent  email.

For full design documentation (will be re-used elsewhere as well), we need to add the design of the upload button after a file has been added.

Can be a simple something similar to our tag design with file-icon, file-name and an option to remove.
