### ISSUE TITLE
(EUR 80) Create onboarding wizard sections

### ISSUE THREAD

**Issue by davidsemakula** [tunga-io/tunga-web#351]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[x] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Expected behavior

All components are already connected to the redux store and receive `Auth`, `Profile` and `ProfileActions` as props.
Find current user's object at `Auth.user`
Save with `ProfileActions.updateProfile`

Visit localhost:8080/onboard to access the wizard in the development environment

- Intro:
https://app.zeplin.io/project/5977533d141d9d52ca3e175d/screen/5b1e6ed2a81ac0b0313e2a8f
Access at: /onboard/intro
Implement at https://github.com/tunga-io/tunga-web/blob/develop/src/components/onboard/Intro.jsx

- Step One:
https://app.zeplin.io/project/5977533d141d9d52ca3e175d/screen/5b1a7a5a5e9932005f94c6bc
Access at: /onboard/step-one
Implement at https://github.com/tunga-io/tunga-web/blob/develop/src/components/onboard/StepOne.jsx

- Step Two:
https://app.zeplin.io/project/5977533d141d9d52ca3e175d/screen/5b1a7a5a57a0c54542b9cb62
Access at: /onboard/step-two
Implement at https://github.com/tunga-io/tunga-web/blob/develop/src/components/onboard/StepTwo.jsx

- Step Three:
https://app.zeplin.io/project/5977533d141d9d52ca3e175d/screen/5b1a7a59e490ad6a5429eeea
Access at: /onboard/step-three
Implement at https://github.com/tunga-io/tunga-web/blob/develop/src/components/onboard/StepThree.jsx

- Finish:
https://app.zeplin.io/project/5977533d141d9d52ca3e175d/screen/5b1a7a15ce9f5b38704a0638
Access at: /onboard/finish
Implement at https://github.com/tunga-io/tunga-web/blob/develop/src/components/onboard/Finish.jsx

Successful saves will lead to `Profile.isSaved.profile` changing to true.
While errors will lead to `Profile.errors.profile` containing a dictionary of errors for each affected field.

Use `ProfileActions.getCountries` to get a list of countries access and access the list at `Profile.countries`

Refer to the Data dictionary and API explorer for the appropriate field names to use for saving data and parsing errors.

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by raheemazeezabiodun** [comment]
on it
