### ISSUE TITLE
As a Tunga admin I would like to see the project margin of each project.

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#370]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[ ] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Enhancement
</code></pre>

As an Tunga admin (David, Domieck, Bart, Ernesto), I should be able to view project margin (payment-payouts=margin). This should be viewable in the payment tab of the project.

**Comment by bartleijssenaar** [comment]
The design is very simple:

![margin design](https://user-images.githubusercontent.com/12690878/44596583-ffb4b500-a7cc-11e8-9f9e-513fe170edcb.jpg)

**Comment by davidsemakula** [comment]
@remo4sam simply the sum of all sales invoice amounts minus sum of all purchase invoice amounts
Add as property on Project model and serializer
