### ISSUE TITLE
(EUR 240) As an Admin or PM I would like to send out bulk emails to developer with a specific profiles (based on skill tags)

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#371]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

As a Tunga staff member (admin or pm), I should be able to send an email to a specific group of developers on Tunga. 
Eg looking for php developer: I fill in project details (short description, skills, project period, expected total hours for dev, etc), then all devs in database who are tagged with php receive an e-mail with two buttons: YES I'm potentially interested in this project, NO I'm not available for this project.

The form on Tunga shall look like this: (design will follow)

Skill tags you want to target:
Project description:
Estimated project size:

When they say YES I'm interested Tunga need to be notified by Slack. 

The template for this

![screen shot 2018-08-20 at 13 54 54](https://user-images.githubusercontent.com/12690878/44339161-ac66fd80-a480-11e8-86af-716cc42713fa.png)

**Comment by bartleijssenaar** [comment]
The designs can be found in Zeplin with tag `dev message (#371)`

**Comment by bartleijssenaar** [comment]
The `opportunity` flow. 

An admin or PM can broadcast an email blast to developers on Tunga. This is based on the skills required for this `opportunity`. When the required skill matches the profile of the developer an email should be sent. 

The screen to broadcast this message looks like this:
![creating opportunity](https://user-images.githubusercontent.com/12690878/44533182-38815b00-a6f5-11e8-9005-553a371cc4a1.jpg)
Admins & PM can access this screen when clicking on the `+` icon on the project tab. 
First there was only the tab `create new project`. Now it will show `create opportunity` as well.

When the user fills in all the screen the following email will be sent. This template can be found in Mandrill (82)

![screen shot 2018-08-23 at 16 58 48](https://user-images.githubusercontent.com/12690878/44533455-dd039d00-a6f5-11e8-8d2c-c7f2795e72c9.png)

**Comment by bartleijssenaar** [comment]
The developer can view opportunities in 2 ways

1) Via Tunga
2) Via Email

1)

The developer also has an overview of the opportunities that match his skill set. The overview will look like this:

![opportunity overview devs](https://user-images.githubusercontent.com/12690878/44574406-a11a1780-a789-11e8-8784-aa0fbfaea7b2.jpg)

An overview of all relevant opportunities is displayed. In each card, the user can find the opportunity title plus a list of required skills. 

When clicking on an opportunity card the developer user sees the following:

![opportunity details developer](https://user-images.githubusercontent.com/12690878/44574773-a330a600-a78a-11e8-9073-d5c7257bd4a9.jpg)

The user can express if he is available by clicking one of the buttons. 
When the user clicks one of the two options, he/she gets a success notification 
If you click one, you can still change your availability. 

![opportunity details developer](https://user-images.githubusercontent.com/12690878/44574963-26ea9280-a78b-11e8-8e16-66bc54273b2a.jpg)
![opportunity details developer a](https://user-images.githubusercontent.com/12690878/44574983-3964cc00-a78b-11e8-976d-6277515a4480.jpg)

2) Via Email

When the user clicks `I'm availiable and interested` (s)he goes to the following page

![opportunity details developer a](https://user-images.githubusercontent.com/12690878/44575155-a4ae9e00-a78b-11e8-93bf-435ff03f78df.jpg)

When the user clicks `I'm not availiable for this project` (s)he goes to the following page

![opportunity details developer](https://user-images.githubusercontent.com/12690878/44575181-b728d780-a78b-11e8-9917-f4985b02d0bb.jpg)

**Comment by bartleijssenaar** [comment]
All designs can be found in Zeplin with tag : `opportunity` @davidsemakula

**Comment by davidsemakula** [comment]
@raheemazeezabiodun 
Ignore emails and Slack notifications
Opportunities are [Projects](http://resources.tunga.io/docs/data-dictionary#idProject) with `stage` set to `opportunity`
Filter opportunities with `/projects/?stage=opportunity` from projects endpoint (Reuse existing actions and reducers)
To upgrade an opportunity to a project (`Activate project`), set `stage` to `active`

Manage user response to the opportunity using the `/interest-poll/`endpoint which manages [InterestPoll](http://resources.tunga.io/docs/data-dictionary#idInterestPoll) objects.
Filter with status parameter e.g `/interest-poll/?status=interested`

Use handling of Participation actions, reducers functions and connectors for inspiration

**Comment by raheemazeezabiodun** [comment]
On it
