### ISSUE TITLE
Automatically strip domains from usernames autogenerated from emails

### ISSUE THREAD

**Issue by davidsemakula** [tunga-io/tunga-web#379]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[x] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Current behavior

Currently, for users invited or created via /network/invite, email is automatically used as the username

## Expected behavior

The email should still be used to generate a username but the domain part should be stripped e.g tdsemakula for tdsemakula@gmail.com. In case a username exists, automatically add a number to the end of the name to break the collision.

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by bartleijssenaar** [comment]
@remo4sam how can I QA this baby? I think it is only doable on production, right?
