### ISSUE TITLE
Widget for CTAs

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#385]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Current behavior

None

## Expected behavior

Web:

On right side, centred on the vertical axis of the screen a CTA widget will be shown. When this widget is not hovered only the (3) icons are shown in a red boxes. When the widget is hovered anywhere on the white (opacity 0.3) box or the red boxes the widget sizes increases in width. Preferably there is a effect when the box increases in size (that you see the boxes increase in size). 

When hovered the text is shown as indicated below. 

Both designs can be found in Zeplin (filter = widget)
Icons can be found here: https://drive.google.com/drive/u/0/folders/1fvNsUE8zAPoDU5v1WZJnacxW3oSV48z2

Mobile:

Only the chat icon is visible (see zeplin for design), when clicked the user widget hover design is shown.

Note: The Chat funtion will remain the same

_Design preview blow_

![screenshot 2018-11-05 at 08 05 58](https://user-images.githubusercontent.com/12690878/47993538-024a5980-e0f0-11e8-9191-a4b3bc6c888c.png)

**Comment by davidsemakula** [comment]
@bartleijssenaar we need better contrast ratio btn text color and background

**Comment by bartleijssenaar** [comment]
Did you try I out? We can change the opacity of the bg to .4 or .5.
