### ISSUE TITLE
Whitepaper page 

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#387]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

Next week, Tunga will publish a white paper. For users to be able to download the whitepaper, we need a landing page with a download btn. 

On the page, we will have the following assets

- the standard Tunga banner size 400px height
- Title (centred)
- Explanation text
- submission form for email address (standard Tunga format for form)
- download button
- preview of the first page of the whitepaper (white square on the page). this will be an a4 format with a width of 70% of the screen size

User journeys for downloading:

1.

- users fill in his/her business email
- clicks download
- file downloads

2. 

- the user clicks download
- email form box lights up (red) as indicated on the design in Zeplin
- proceeds with 1. 

Design can be found on Zeplin

![white paper 1](https://user-images.githubusercontent.com/12690878/49422585-c6f58600-f794-11e8-9201-96c299b5425f.jpg)

**Comment by raheemazeezabiodun** [comment]
Well received

**Comment by raheemazeezabiodun** [comment]
@bartleijssenaar can you provide the background image used in preview
