### ISSUE TITLE
New payment and invoice flow

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#398]
Currently, an invoice gets send to a client when a PM or Admin creates a payment. When a payment gets updated a new invoice gets send with the current invoice number. 

The following must chance to have a clear and structured way of sending out invoices to Tunga's clients.

- Splitting up the invoice into 2 concepts: Payments and Invoices

Payment is when a PM or ADMIN creates a payment (Amount, title and date) in the system. When this is submitted, it can still be adjusted but NONE of the users on the platform is able to download an invoice. 

Invoices can only be generated by the ADMIN. When a payment is due (based on the date), a notification is sent to Slack to notify that an ADMIN user should 
1. Generate the invoice or
2. Change the payment date 

- When the ADMIN decides to generate an invoice, the invoice gets send to the client. This invoice CANNOT be adjusted after sending. If there is anything incorrect on the invoice a CREDIT NOTA (#393) should be created and a new invoice should be created.

**Comment by bartleijssenaar** [comment]
@davidsemakula can you let me know if everything is clear and if you have any comments? Then I will proceed by creating the designs.

**Comment by bartleijssenaar** [comment]
Please note, these are 'design' created with the inspect function of chrome.

When a PM creates a payment:
![screenshot 2019-01-24 at 11 59 58](https://user-images.githubusercontent.com/12690878/51675571-57518980-1fd4-11e9-9ddd-f302d55bedf6.png)
Please note that an ADMIN user can also see the btn to credit nota (see below)

An admin can generate an invoice:
note: all other options in the popup will disappear. The pm can only edit or delete but CANT generate an invoice. 
![screenshot 2019-01-24 at 11 51 54](https://user-images.githubusercontent.com/12690878/51675766-f080a000-1fd4-11e9-9ebc-82e70096a97b.png)
edit: invoice tabs will say: invoice / credit nota

Credit nota (#393) ONLY FOR ADMINS

![screenshot 2019-01-24 at 12 03 44](https://user-images.githubusercontent.com/12690878/51676016-a9df7580-1fd5-11e9-8f7b-91e68243917a.png)

![screenshot 2019-01-24 at 12 25 43](https://user-images.githubusercontent.com/12690878/51676026-b368dd80-1fd5-11e9-8518-172dd62be0c5.png)

The credit nota ends up in the invoice list but with (-) <-- a negative amount 

![screenshot 2019-01-24 at 12 51 35](https://user-images.githubusercontent.com/12690878/51676415-d2b43a80-1fd6-11e9-86bf-83b3d2b20804.png)

Permissions:

PM is able to create, edit and delete a payment  
Admin is able to create, edit and delete a payment
Admin is able to create a credit nota
Admin is able to generate an invoice based on a payment


Notifications:

**Comment by davidsemakula** [comment]
@remo4sam let's discuss technical details when you're ready to pick this up
