### ISSUE TITLE
Tunga coding test

### ISSUE THREAD

**Issue by reiniervs** [tunga-io/tunga-web#399]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[ ] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Enhancement
</code></pre>

## Current behavior

If we want to check whether a developer actually knows how to code in a specific language, we either rely on third party tools (expensive), in depth code reviews/interviews (time consuming) or factual experience on projects (liability).

## Expected behavior

I would like to be able to send a self-developed Tunga coding test for specific languages to all developers on the Tunga platform that put that language in their profile. If the developer passes, I'd like their language button to turn green as in affirmative. If they don't pass, I'd like that language to be removed from their profile. As an added bonus, over time we'll acquire a library of coding tests to further improve our quality.

## What is the motivation / use case for changing the behavior?

To make the developer onboarding scalable and increase our quality.

## Requested Delivery Date (feature requests only):
01/02/2019

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
- [x] Other version XX 

Operating System:
- [x] macOS version XX
- [x] Windows version XX
- [x] Linux  XX
- [x] Android version XX
- [x] iOS version XX
- [x] Windows Phone version XX
- [x] Other version XX 

Environment/ Server:
- [x] Production
- [x] Staging
- [x] Test
- [x] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

I propose to start with the language we have the most on our platform. I reckon that is PHP, but if it's another one let's use that

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by bartleijssenaar** [comment]
@davidsemakula will compile 10 questions and sample assignment for React.
Deadline Monday 18th of Feb.

**Comment by gerodur** [comment]
@bartleijssenaar I reached out to testdome.com. They offer API access https://testdome.com/api/v1/help 

From what I gather, we would:
- Create an account on testdome.com, then 
- Create a bunch of tests eg ReactJS, angularJS, Django etc
- Use the API to invite a candidate to a test (or view them from the account we create)
- Use the API to get results from the test (or view them from the account we create)

A concern is the pricing. What do you think of it
