### ISSUE TITLE
Assess coding performance of TUNGA developers

### ISSUE THREAD

**Issue by reiniervs** [tunga-io/tunga-web#402]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[x] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Current behavior

At the moment, we don't have any data about the performance of developers that work for Tunga.

## Expected behavior

We'd like to investigate what possible data we can use from developers working for Tunga to assess or indicate their performance

## What is the motivation / use case for changing the behavior?

With more data about performance we can better assess which developers are good, and which aren't. And we can use this data to convince our clients and improve on our coding standards

## Requested Delivery Date (feature requests only):
08/02/2019

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by bartleijssenaar** [comment]
@davidsemakula let's pick this one up later today in the #product channel. I know @espruyt and @reiniervs also have thoughts on this one.

**Comment by gerodur** [comment]
@bartleijssenaar was there more information given on this feature?
