### ISSUE TITLE
Quiz to assess comprehension of Tunga Developer Guide

### ISSUE THREAD

**Issue by reiniervs** [tunga-io/tunga-web#404]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[ ] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Enhancement
</code></pre>

## Current behavior

At the moment, we send the Tunga development guide and take it for granted that the developer actually reads and understands it.

## Expected behavior

When a developer clicks on the 'I'm interested' button of a new opportunity, he/she will be directed to a page where the Tunga developer guide is downloaded. When the download is complete, a quiz will appear with 5 crucial multiple-choice questions from the guide, for the developer to answer. When all have been answered correctly, a message stating we now conclude they have read and understood the Tunga developer guide is shown and his/her profile will be shared with the opportunity lead.

## What is the motivation / use case for changing the behavior?

To make sure the developers have read and understood the Tunga Developer guide

## Requested Delivery Date (feature requests only):
10/02/2019

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by bartleijssenaar** [comment]
This will be assigned to me @davidsemakula. I will create the 5 questions plus the format from the wizard with questions. I will use an existing template for the wizard.

**Comment by gerodur** [comment]
@bartleijssenaar any luck designing the questions

**Comment by bartleijssenaar** [comment]
https://docs.google.com/document/d/1v2TwJWYBZG1R0eTtYakCioSzkxCt2VxsK08wgKTF_58/edit

**Comment by gerodur** [comment]
@bartleijssenaar any chance you could share a design for this?

**Comment by gerodur** [comment]
@bartleijssenaar any luck with designs for this or do we have Boma to look at it?

**Comment by bartleijssenaar** [comment]
This is me. Still working on it.

**Comment by gerodur** [comment]
@bartleijssenaar any luck finishing this?
