### ISSUE TITLE
Chat Messaging with Slack Integration

### ISSUE THREAD

**Issue by dukedanny** [tunga-io/tunga-web#417]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[x ] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Current behavior

Presently, a platform visitor schedules a call with a Tunga representative using Calendly embed. 

## Expected behavior

Communication between a platform visitor and a Tunga representative should be directed straight to a channel on our internal chat tool, Slack. 

## What is the motivation / use case for changing the behavior?

Reduce the number of steps and time required to capture a lead directly from the platform.

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

TBC

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by gerodur** [comment]
@bartleijssenaar is this still going to be done?

**Comment by bartleijssenaar** [comment]
Intercom only @gerodur

**Comment by gerodur** [comment]
ok
