### ISSUE TITLE
Implement News Page

### ISSUE THREAD

**Issue by dukedanny** [tunga-io/tunga-web#429]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[ ] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Expected behavior

Goal: keep website visitors informed about the latest at Tunga

**Elements**

## Entire News page
![Screenshot 2019-05-16 at 14.42.07.png](https://images.zenhubusercontent.com/5cc3b145cd78cd6a07eb0879/cc015431-0512-4d4f-8bb3-e3966dde4a63)

- Articles summary structure
<img width="631" alt="Screen Shot 2019-04-18 at 06 33 43" src="https://user-images.githubusercontent.com/437728/56335126-f33dfc00-61a3-11e9-94ba-79d482a9a879.png">

- Vlogs structure
<img width="608" alt="Screen Shot 2019-04-18 at 06 34 17" src="https://user-images.githubusercontent.com/437728/56335148-0781f900-61a4-11e9-9803-e715ddf57698.png">

- Vlog structure (on click)
<img width="636" alt="Screen Shot 2019-04-18 at 06 35 08" src="https://user-images.githubusercontent.com/437728/56335179-27192180-61a4-11e9-8630-f9994507e996.png">

- White paper summary structure (with download button)
<img width="631" alt="Screen Shot 2019-04-18 at 06 35 52" src="https://user-images.githubusercontent.com/437728/56335201-41eb9600-61a4-11e9-9886-af45a631849d.png">

- White paper download structure (on clicking download button)
Details to be captured (All required)
1. Full Name
2. Company/ Organisation
3. Business Email
4. Phone Number
5. Country

<img width="634" alt="Screen Shot 2019-04-18 at 06 36 51" src="https://user-images.githubusercontent.com/437728/56335240-65164580-61a4-11e9-9ab1-43bcf09aa012.png">

- Blog summary structure
<img width="634" alt="Screen Shot 2019-04-18 at 06 39 28" src="https://user-images.githubusercontent.com/437728/56335329-bf170b00-61a4-11e9-90ba-8f039bcca1a7.png">

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by gerodur** [comment]
Responsive view:

![Screen Shot 2019-05-02 at 17.57.39.png](https://images.zenhubusercontent.com/5cc3b145cd78cd6a07eb0879/90eb7713-8285-443e-bbda-660b43d38f30)![Screen Shot 2019-05-02 at 17.58.33.png](https://images.zenhubusercontent.com/5cc3b145cd78cd6a07eb0879/d97de846-43f9-4242-b309-2f9c429583f1)

**Comment by gerodur** [comment]
@davidsemakula 6 hours?
