### ISSUE TITLE
Implement Blog Post Page

### ISSUE THREAD

**Issue by dukedanny** [tunga-io/tunga-web#430]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[ ] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Enhancement
</code></pre>

## Expected behavior

 Goal: Express brand identity and visibility through intuitive blog content

Elements
- Title
- Author
- Content
- Recommended content

<img width="629" alt="Screen Shot 2019-04-18 at 06 47 15" src="https://user-images.githubusercontent.com/437728/56335610-d6a2c380-61a5-11e9-8ace-379acb9ae1ed.png">

## Requested Delivery Date (feature requests only):
dd/MMM/YYYY

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

Requested Delivery Date: dd/MMM/YYYY

</code></pre>

**Comment by gerodur** [comment]
@davidsemakula 2 hours?

**Comment by kingstuffy** [comment]
Time required: 3hrs
