### ISSUE TITLE
Implement "Our Services" section on homepage

### ISSUE THREAD

**Issue by gerodur** [tunga-io/tunga-web#435]
## I'm submitting a ...

<pre><code>

[x] Feature request
[ ] Enhancement
</code></pre>

## Explanation

Just below the about section, we have the Our Services section. Our services shows a horizontal carousel of the services offered by Tunga and a summary of the use cases for the services to help guide the user on their choices. 

The horizontal scroll on services is activated by the left right arrows.
  

![services-responsive-1](https://user-images.githubusercontent.com/49911346/56738219-d346a380-6774-11e9-87fd-883c83c33f16.png)
![#home_mobile_services_layover](https://user-images.githubusercontent.com/49911346/56738221-d3df3a00-6774-11e9-99a4-88bd3f547cf4.png)
![#3](https://user-images.githubusercontent.com/49911346/56738246-e194bf80-6774-11e9-94b3-5ff6779872c0.png)
![#home_services_layover](https://user-images.githubusercontent.com/49911346/56738249-e22d5600-6774-11e9-96da-36f1effa1ed7.png)

**Read Now**:
In the use cases section, a use case title and a `Read now` button are available.  When `Read now` is clicked:
- The page scrolls to the "Case Studies" section on the homepage.
- The use case from which `Read now` was clicked is shown as the open/fully displayed use case

**Assets Folder**:
https://drive.google.com/drive/folders/1lQ7Un4mReUobEUN1u5gDpY8iy-jFdJpB

##Environment 
<pre><code>
Responsive web
</code></pre>

**Comment by gerodur** [comment]
@davidsemakula 1 hour

**Comment by Procaseycash** [comment]
Considering the card design here and and navigation. 1hr is not feasible. Also I can see an overview screen where user can close. This sum up to two different screens.
