### ISSUE TITLE
Implement the new case studies section of the proposed design on the homepage

### ISSUE THREAD

**Issue by gerodur** [tunga-io/tunga-web#436]
## I'm submitting a ...

<pre><code>
[x] Feature request
</code></pre>

## Current

Current implementation can be found on tunga.io below the video section

## Proposed

Proposed design will feature text in cards on the left and an image graphic on the right, just below the Schedule a call cover section. 

In the cards, different case studies will be accessible by horizontal carousel using arrows 

![case studies img](https://user-images.githubusercontent.com/49911346/56798496-823fb980-681f-11e9-88ee-3dce832db1b1.png)
![case study responsive](https://user-images.githubusercontent.com/49911346/56798735-0c881d80-6820-11e9-8c40-7498c7df0132.png)

Asset Resources
https://drive.google.com/drive/folders/1MzZsbC3Op93Bv5bJsQvZscG_MEHx34_1

##Environment 

<pre><code>

Responsive web

</code></pre>

**Comment by gerodur** [comment]
@davidsemakula 3 hours?

**Comment by Procaseycash** [comment]
@gerodur This should be 4hrs considering responsiveness, content design and horizontal pagination.
