### ISSUE TITLE
Tunga SSL issue

### ISSUE THREAD

**Issue by gerodur** [tunga-io/tunga-web#443]
![image (5)](https://user-images.githubusercontent.com/49911346/57911730-35d12200-7891-11e9-9263-a4cadb1a795e.png)

## Priority
Highest 

Expired: Friday, 17 May 2019 at 02:59:59 East Africa Time

**Comment by gerodur** [comment]
@bartleijssenaar you will have to purchase a new SSL certificate ~ Remo

**Comment by davidsemakula** [comment]
Fixed @gerodur
