### ISSUE TITLE
Assign a label to a project

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#457]
We would like to have a label assigned to each project. The label is assigned when creating a project and can be edited in the settings of a project. 

There are 3 different labels
-  Project
- Dedicated
- Internal

Designs below and can be found on Zeplin with tag #457:

![Project_label](https://user-images.githubusercontent.com/12690878/58809924-2ab21c00-861d-11e9-80fd-47bfe15f7d67.jpg)
![Project_label_settings](https://user-images.githubusercontent.com/12690878/58809923-2a198580-861d-11e9-9ae5-f4cc476a939c.jpg)

**Comment by gerodur** [comment]
@aleku399 this one already has a design

**Comment by gerodur** [comment]
@kingstuffy after completing the issues on Trello you can look into this
