### ISSUE TITLE
Monitoring Tasks

### ISSUE THREAD

**Issue by davidsemakula** [tunga-io/tunga-web#7]
***Monitoring***

1) Monitoring workflow

Based on the preferences given by the PO the developer(s) working on the task receive an email and a notification that they HAVE to fill in a small form. 

The developer(s) can fill in the form on the Tunga platform.  Once the developer clicks on the link in the email the developer gets directed to the workflow page with a pop-up with the following questions:

Checkbox with “what is the task status” with predefined statuses. E.g ‘on schedule’, ‘stuck’, ‘behind’, etc 
How many % of the task is finished [field where they can fill in numerical value between 0 and 100]
What work did you do in the last day, 2 days, 3 days etc. (based on the preferences of the PO); maximum amount of characters (400) to force them to be concise
there should be a field where the developer upload files to showcase his progress. 
Next step(s) [max characters to keep it concise]
Other remarks
[this form should be very brief]

The (daily, 2 day, etc) update is presented as a message in the workflow tool and send directly to the project owner in an email (or if he wishes to receive only a notification, he only receives a notification)

-subtask this has to be a setting option.

The project owner can comment on the update form of the developer(s) in the workflow page. 

2) Mile stones

The project owner should be able to set certain milestones throughout the task period set by the project owner. This feature is very useful when a task takes longer than a couple of days. 

The PO can select when he wants certain features or parts from the code delivered. We will call these milestones on Tunga. The PO should be able to fill in milestones on the “create a new task page”

The PO should able to fill in milestones, a milestone means the developer should deliver a piece of the code of a print screen/live demo work already done. 

A fixed milestone has to be ”submit final draft” a day before the deadline (when the task is below 150$

A fixed milestone has to be ”submit final draft”  TWO days before the deadline (when the task is above 150$

A fixed milestone will be each reporting moment, depending on the PO’s task update frequency preferences

Other mile stones can be filled in by the PO.

__Design will follow__

3) Task timeline

On the workflow page, there must a visual timeline.  On the “task timeline” there must be the following details about the task presented. 

Creation of the task (date): this should be the date on which the task was created. 
Team complete for task: final selection of developer(s) submitted 
Updates 
Milestones
Deadline. 
 

__Design will follow__

**Comment by mossplix** [comment]
What is the current workflow/ what is existing?

**Comment by mossplix** [comment]
I think the primary notification should be inapp. Email should be the backup incase some one has not received/read the notification.

**Comment by mossplix** [comment]
I am adding channels for the real communications bit i.e if we move away from email as the primary notification gateway .

**Comment by davidsemakula** [comment]
@mossplix this issue has been split further to make it more concise
