### ISSUE TITLE
When I save my details on profile I don't see my the notification 

### ISSUE THREAD

**Issue by bartleijssenaar** [tunga-io/tunga-web#89]
I save my details but the notification is not showing

![screen shot 2016-08-05 at 15 29 34](https://cloud.githubusercontent.com/assets/12690878/17438667/5a18cd94-5b24-11e6-9ad9-a053228c8bd7.png)

up top is the notification 

![screen shot 2016-08-05 at 15 53 44](https://cloud.githubusercontent.com/assets/12690878/17438766/cfb03268-5b24-11e6-864f-3d2b21c2a3f9.png)

It must be visible in the screen that the user is looking at

**Comment by davidsemakula** [comment]
I did a temporary scroll fix for this issue.
I will create an issue for updating the way these notifications are presented site wide
